
        name: Build Cutting List App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Windows Installer
        run: npm run build

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: CuttingListApp-v${{ github.run_id }}-windows-x64.exe
          path: dist/*.exe
          echo Add other actions to build,
          echo test, and deploy your project.
