name: Build Cutting List App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Windows App
        run: npm run build

      - name: Package Electron App for Windows
        run: npx electron-builder --win --x64

      - name: Upload Windows EXE Installer
        uses: actions/upload-artifact@v4
        with:
          name: CuttingListApp-v${{ github.run_number }}-${{ github.run_id }}-windows-x64.exe
          path: |
            dist/*.exe
            dist/*.msi
